version: '3.8'

services:
  room-service:
    build: ./RoomService
    ports:
      - "8081:8080"

  booking-service:
    build: ./BookingService
    ports:
      - "8082:8081"

  approval-service:
    build: ./ApprovalService
    ports:
      - "8083:8081"